"""goal challenge one to one fixed

Revision ID: 399b70c0b942
Revises: 2bede0009a58
Create Date: 2026-10-03 21:03:35.720405

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "399b70c0b942"
down_revision: Union[str, Sequence[str], None] = "2bede0009a58"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("challenge", sa.Column("goal_id", sa.UUID(), nullable=False))
    op.create_foreign_key(None, "challenge", "goal", ["goal_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, "challenge", type_="foreignkey")
    op.drop_column("challenge", "goal_id")
    # ### end Alembic commands ###
