"""link balance to user group

Revision ID: 56a6ae2a89a7
Revises: d190327e6de7
Create Date: 2026-10-03 19:59:22.366615

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "56a6ae2a89a7"
down_revision: Union[str, Sequence[str], None] = "d190327e6de7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "group_member_balance", sa.Column("user_group_id", sa.UUID(), nullable=False)
    )
    op.create_unique_constraint(None, "group_member_balance", ["user_group_id"])
    op.create_foreign_key(
        None, "group_member_balance", "user_group", ["user_group_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, "group_member_balance", type_="foreignkey")
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, "group_member_balance", type_="unique")
    op.drop_column("group_member_balance", "user_group_id")
    # ### end Alembic commands ###
