"""Add deactivation

Revision ID: ab6e7352130d
Revises: a71c4d98e203
Create Date: 2026-10-04 01:09:29.078079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab6e7352130d'
down_revision: Union[str, Sequence[str], None] = 'a71c4d98e203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_group', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_group', 'active')
    # ### end Alembic commands ###
