"""db-init

Revision ID: b3ab8c1f6336
Revises: 324958927aa2
Create Date: 2026-10-03 18:20:04.863548

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b3ab8c1f6336"
down_revision: Union[str, Sequence[str], None] = "324958927aa2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "foundation",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "group",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "group_member_balance",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("balance", sa.Numeric(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("e-mail", sa.Text(), nullable=False),
        sa.Column("role", sa.Enum("USER", "ADMIN", name="user_role"), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("e-mail"),
    )
    op.create_table(
        "challenge",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("foundation_id", sa.UUID(), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column(
            "state",
            sa.Enum("ACTIVE", "COMPLETED", "FAILED", name="challenge_state"),
            nullable=False,
        ),
        sa.Column(
            "addiction_type",
            sa.Enum("ALCOHOL", "NICOTINE", "GAMBLING", "OTHER", name="addiction_type"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["foundation_id"],
            ["foundation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_group",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["group.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "goal",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("saldo", sa.Integer(), nullable=False),
        sa.Column(
            "period",
            sa.Enum("DAILY", "WEEKLY", "MONTHLY", name="goal_period"),
            nullable=False,
        ),
        sa.Column("challenge_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["challenge_id"],
            ["challenge.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "gift_goal",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["goal.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("gift_goal")
    op.drop_table("goal")
    op.drop_table("user_group")
    op.drop_table("challenge")
    op.drop_table("user")
    op.drop_table("group_member_balance")
    op.drop_table("group")
    op.drop_table("foundation")
    # ### end Alembic commands ###
