"""Add subscriptions

Revision ID: cb9725ee90e2
Revises: 399b70c0b942
Create Date: 2026-10-04 00:32:03.926831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb9725ee90e2'
down_revision: Union[str, Sequence[str], None] = '399b70c0b942'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscription',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.Text(), nullable=False),
    sa.Column('auth', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.drop_constraint(op.f('challenge_goal_id_fkey'), 'challenge', type_='foreignkey')
    op.drop_column('challenge', 'goal_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge', sa.Column('goal_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('challenge_goal_id_fkey'), 'challenge', 'goal', ['goal_id'], ['id'])
    op.drop_table('push_subscription')
    # ### end Alembic commands ###
