"""change goal name

Revision ID: d190327e6de7
Revises: b3ab8c1f6336
Create Date: 2026-10-03 19:24:11.770026

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d190327e6de7"
down_revision: Union[str, Sequence[str], None] = "b3ab8c1f6336"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("challenge", "description")
    op.drop_column("challenge", "name")
    op.alter_column(
        "gift_goal",
        "price",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=False,
    )
    op.alter_column(
        "goal",
        "saldo",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=False,
    )
    op.drop_column("goal", "description")
    op.drop_column("goal", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "goal", sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "goal", sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False)
    )
    op.alter_column(
        "goal",
        "saldo",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "gift_goal",
        "price",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.add_column(
        "challenge", sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "challenge",
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
